export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <title>Login | Board.</title>
      <div>{children}</div>
    </>
  );
}
